hms_doctor_commission_invoice:
    path:     /
    defaults: { _controller: "HospitalBundle:DoctorInvoice:index" }

hms_doctor_invoice:
    path:     /doctor
    defaults: { _controller: "HospitalBundle:DoctorInvoice:doctorInvoice" }

hms_doctor_invoice_show:
    path:     /{id}/show
    defaults: { _controller: "HospitalBundle:DoctorInvoice:show" }

hms_doctor_invoice_new:
    path:     /{id}/new
    defaults: { _controller: "HospitalBundle:DoctorInvoice:new" }


hms_doctor_invoice_create:
    path:     /{id}/create
    defaults: { _controller: "HospitalBundle:DoctorInvoice:create" }
    methods:  [POST]

hms_doctor_invoice_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:DoctorInvoice:delete" }

hms_doctor_invoice_pay:
    path:     /{id}/pay
    defaults: { _controller: "HospitalBundle:DoctorInvoice:pay" }

hms_doctor_invoice_confirm:
    path:     /{id}/invoice-confirm
    defaults: { _controller: "HospitalBundle:DoctorInvoice:confirm" }



