hms_pathological_report:
    path:    /{pathology}
    defaults: { _controller: "HospitalBundle:PathologicalReport:pathologicalReport" }

hms_pathological_report_create:
    path:      /{pathology}/create
    defaults: { _controller: "HospitalBundle:PathologicalReport:create" }
    methods:  POST

hms_pathological_report_edit:
    path:      /{pathology}/{id}/edit
    defaults: { _controller: "HospitalBundle:PathologicalReport:edit" }

hms_pathological_report_update:
    path:      /{pathology}/{id}/update
    defaults: { _controller: "HospitalBundle:PathologicalReport:update" }
    methods:  [POST, PUT]

hms_pathological_report_delete:
    path:      /{pathology}/{id}/delete
    defaults: { _controller: "HospitalBundle:PathologicalReport:delete" }

hms_pathological_report_status:
    path:      /{pathology}/{id}/status
    defaults: { _controller: "HospitalBundle:PathologicalReport:status" }

hms_pathological_report_list_sorted:
    path:      /sorted/{pathology}
    defaults: { _controller: "HospitalBundle:PathologicalReport:sorting" }
    methods:  POST


